applicationName: Sample App

database:
  driverClass: com.mysql.jdbc.Driver
  user: atonu
  password: Test1234
  url: jdbc:mysql://dropwizard.cv38onp0huge.ap-south-1.rds.amazonaws.com:3306/db_notes
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
